import { defineAsyncComponent, ComponentCustomOptions } from 'vue';

const list = [
	// Generated by @ripple.tju/train-documentation
	'bcff7859-79a8-4567-a62c-ac524257e922',
	'bcff7859-79a8-4567-a62c-ac524257e923',
];

export const map: Record<string, ComponentCustomOptions> = {};

for (const id of list) {
	map[id] = defineAsyncComponent(() => import(`./instances/${id}.vue`));
}
